export const salaryAndAllowances = [
  {
    name: "Overtime",
    description: "Additional pay for overtime work",
    amount: 0,
    formula: "hourlyRate * 1.25 * overtimeHours",
    type: "addition",
  },
  {
    name: "End of Service Gratuity",
    description: "Gratuity based on UAE labor law",
    amount: 0,
    formula:
      "IF(yearsOfService < 5, basicSalary * yearsOfService * (21/30), basicSalary * 5 * (21/30) + basicSalary * (yearsOfService - 5) * (30/30))",
    isEndOfService: true,
    type: "addition",
  },
  {
    name: "Sick Leave Deduction",
    description: "Deduction for unpaid sick leave",
    amount: 0,
    formula: "dailySalary * unpaidSickDays",
    type: "deduction",
  },
  {
    name: "Performance Bonus",
    description: "Bonus based on employee performance",
    amount: 0,
    formula: "basicSalary * performanceMultiplier",
    type: "addition",
  },
  {
    name: "Sales Commission",
    description: "Commission for sales achievements",
    amount: 0,
    formula: "salesAmount * commissionRate",
    type: "addition",
  },
  {
    name: "Night Shift Allowance",
    description: "Additional pay for night shift work",
    amount: 300,
    type: "addition",
  },
  {
    name: "Holiday Pay",
    description: "Extra pay for working on holidays",
    amount: 0,
    formula: "holidayHours * holidayRate",
    type: "addition",
  },
  {
    name: "Travel Allowance",
    description: "Allowance for business travel expenses",
    amount: 250,
    type: "addition",
  },
  {
    name: "Education Allowance",
    description: "Allowance for employee education or training",
    amount: 400,
    type: "addition",
  },
  {
    name: "Relocation Bonus",
    description: "One-time bonus for relocating employees",
    amount: 0,
    formula: "basicSalary * relocationMultiplier",
    type: "addition",
  },
  {
    name: "Retention Bonus",
    description: "Bonus to retain valuable employees",
    amount: 0,
    formula: "yearsOfService * retentionRate",
    type: "addition",
  },
  {
    name: "Shift Differential",
    description: "Additional pay for non-standard shifts",
    amount: 0,
    formula: "shiftHours * shiftDifferentialRate",
    type: "addition",
  },
  {
    name: "Referral Bonus",
    description: "Bonus for referring new hires",
    amount: 0,
    formula: "referralBonus * successfulReferrals",
    type: "addition",
  },
  {
    name: "Project Completion Bonus",
    description: "Bonus for completing projects on time",
    amount: 0,
    formula: "projectamount * completionBonusRate",
    type: "addition",
  },
  {
    name: "Certification Bonus",
    description: "Bonus for obtaining professional certifications",
    amount: 400,
    type: "addition",
  },
  {
    name: "Meal Allowance Deduction",
    description: "Deduction for provided meals",
    amount: 100,
    type: "deduction",
  },
  {
    name: "Uniform Deduction",
    description: "Deduction for provided uniforms",
    amount: 200,
    type: "deduction",
  },
];
